### ISSUE TITLE
From framer-motion to tailwindcss-animate

### ISSUE THREAD

**Issue by davidsonsns** [Marcosfitzsimons/multi-step-form#1]
Another way to achieve this could be using [`tailwindcss-animate`](https://github.com/jamiebuilds/tailwindcss-animate). Since its already installed, can be a better choice (1 less package, ssr).

eg., in the `app/page.tsx`:

```tsx
from
<AnimatePresence mode="wait">

to
<div className="animate-in fade-in zoom-in">
```

Flagging this because i did something similar in another project. And I thought it would be nice to share with you. 🤌🏻

**Comment by Marcosfitzsimons** [comment]
Thanks for mentioning it Davidson, I will implement it in another project :)

**Comment by Marcosfitzsimons** [comment]
Thanks for mentioning it Davidson, I will implement tailwindcss-animate to add animations in another project :)
